# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    psm1_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

psm1_arm_controller:
  ros__parameters:
    joints:
      - outer_yaw
      - outer_pitch_1
      - outer_insertion
      - outer_roll
      - outer_wrist_pitch
      - outer_wrist_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity